# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Clean up all the details of the table to avoid duplicates
Place.delete_all

#Prefill the table with 5 places
Place.create(:title => 'Charminar', :photo_url => "http://3.bp.blogspot.com/-VW8_PcOFfpk/UfJvjztjYjI/AAAAAAAAAfU/4wrx_NNwGJ0/s1600/Charminar+night+view.jpg", :admission_price => 10,:description => "The Charminar was constructed in the intersection of the historical trade route that connects the markets of Golconda with the port city of Masulipatnam.[13]:195 The Old City of Hyderabad was designed with Charminar as its centerpiece.[14] The city was spread around the Charminar in four different quadrants and chambers, seggregated according to the established settlements. Towards the north of Charminar is the Char Kaman, or four gateways, constructed in the cardinal directions.[7][13] [15] Mir Momin Astarabadi, Qutb Shah's prime minister, played a leading role in preparing the layout plan for the Charminar along with that of the new capital city, Hyderabad.[16]:170 Additional eminent architects from Persia were also invited to develop the city plan. The structure itself was intended to serve as a Mosque and Madraasa. It is of Indo-Islamic architecture style, incorporating Persian architectural elements.")
Place.create(:title => 'Hussain Sagar', :photo_url => "http://hyderabadattractions.com/wp-content/uploads/2012/10/hussain.jpg", :admission_price => 20,:description => "Hussain Sagar is a lake in Hyderabad, Telangana, India, built by Hazrat Hussain Shah Wali in 1562, during the rule of Ibrahim Quli Qutub Shah. It is spread across an area of 5.7 square kilometers and is fed by River Musi. A large monolithic statue of the Gautama Buddha, erected in 1992 stands in an island in the middle of the lake.[1] Maximum depth of the lake is 32 feet.")
Place.create(:title => 'Taj Mahal', :photo_url => "https://tmi2-tourmyindiapvtlt.netdna-ssl.com/blog/wp-content/uploads/2014/10/Taj-Mahal.jpg", :admission_price => 5,:description => "The Taj Mahal is a white marble mausoleum located on the southern bank of Yamuna River in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favorite wife of three, Mumtaz Mahal.")
Place.create(:title => 'Golden Temple', :photo_url => "http://www.thehistoryhub.com/wp-content/uploads/2014/04/Golden-Temple-Night-View.jpg", :admission_price => 15,:description => "Golden Temple is the holiest Sikh gurdwara located in the city of Amritsar, Punjab, India. The city was founded in 1574 by the fourth Sikh guru, Guru Ram Das. The Harmandir Sahib was designed by the fifth guru, Guru Arjan, who had the cornerstone laid by the Muslim Sufi saint Sai Hazrat Mian Mir on 28 December 1588. Guru Arjan completed the Adi Granth, the holy scripture of Sikhism, in 1604 and installed it in the gurdwara ")
Place.create(:title => 'Agra Fort', :photo_url => "https://msdnholidays.files.wordpress.com/2011/02/253408113_083c7e1318_z.jpg", :admission_price => 6,:description => "The Agra Fort is a UNESCO World Heritage site located in Agra, Uttar Pradesh, India. It is about 2.5 km northwest of its more famous sister monument, the Taj Mahal. The fort can be more accurately described as a walled city.")